# Ce fichier est un TEMPLATE.
# Les vraies valeurs sont injectées par le pipeline CI/CD via kubectl create secret
#
# Utiliser la commande suivante pour pouvoir créer le secret manuellement sur la VM :
#
#   kubectl create secret generic todoapp-secrets \
#     --namespace=todoapp \
#     --from-literal=DB_PASSWORD='votre_mot_de_passe' \
#     --from-literal=JWT_SECRET='votre_secret_jwt' \
#     --dry-run=client -o yaml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secrets
  namespace: todoapp
type: Opaque
# Les données sont injectées par le pipeline 
